spring:
  datasource: # 配置数据路连接驱动
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:F:/test1.db
#    jdbc-url: jdbc:sqlite::resource:static/test1.db



mybatis: # 配置mybatis
  type-aliases-package: com.claroja.model # 模型所在目录,xml中的resultType就不用写全类名了
  mapper-locations: classpath:mapper/*Mapper.xml # mapper.xml所在目录